# MariaDB
#
# Access via "http://localhost:8080"
#   (or "http://$(docker-machine ip):8080" if using docker-machine)
version: '3'
services:
  db:
    image: mariadb
    restart: "no"
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: passme
    ports:
      - 3306:3306
    volumes:
      - ./db/data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
